<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6793" started-at="2020-05-22T22:28:27 IST" finished-at="2020-05-22T22:28:34 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6793" started-at="2020-05-22T22:28:27 IST" finished-at="2020-05-22T22:28:34 IST">
      <class name="jiraApiTest.GetAPITests">
        <test-method status="PASS" signature="loginTest()[pri:0, instance:jiraApiTest.GetAPITests@64729b1e]" name="loginTest" is-config="true" duration-ms="176" started-at="2020-05-22T22:28:27 IST" finished-at="2020-05-22T22:28:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="getJiraTestSteptatus(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:jiraApiTest.GetAPITests@64729b1e]" name="getJiraTestSteptatus" duration-ms="4347" started-at="2020-05-22T22:28:28 IST" data-provider="getTestData" finished-at="2020-05-22T22:28:32 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[/rest/raven/1.0/api/settings/teststepstatuses]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Content-Type]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[application]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[json]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [403] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [403] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at jiraApiTest.GetAPITests.getJiraTestSteptatus(GetAPITests.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getJiraTestSteptatus -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:jiraApiTest.GetAPITests@64729b1e]" name="getResult" is-config="true" duration-ms="31" started-at="2020-05-22T22:28:32 IST" finished-at="2020-05-22T22:28:32 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getJiraTestSteptatus status=FAILURE method=GetAPITests.getJiraTestSteptatus(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:jiraApiTest.GetAPITests@64729b1e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="getJiraTestSteptatus(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:jiraApiTest.GetAPITests@64729b1e]" name="getJiraTestSteptatus" duration-ms="948" started-at="2020-05-22T22:28:32 IST" data-provider="getTestData" finished-at="2020-05-22T22:28:33 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[/rest/raven/1.0/api/settings/teststepstatuses]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Content-Type]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[application]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[json]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [403] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [403] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at jiraApiTest.GetAPITests.getJiraTestSteptatus(GetAPITests.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getJiraTestSteptatus -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:jiraApiTest.GetAPITests@64729b1e]" name="getResult" is-config="true" duration-ms="7" started-at="2020-05-22T22:28:33 IST" finished-at="2020-05-22T22:28:33 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getJiraTestSteptatus status=FAILURE method=GetAPITests.getJiraTestSteptatus(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:jiraApiTest.GetAPITests@64729b1e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:jiraApiTest.GetAPITests@64729b1e]" name="teardown" is-config="true" duration-ms="472" started-at="2020-05-22T22:28:33 IST" finished-at="2020-05-22T22:28:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- jiraApiTest.GetAPITests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
